contact_links:
  - name: Discussions
    url: https://github.com/CCBR/MOSuite-Galaxy/discussions
    about: Please ask and answer questions here.
  - name: R Package
    url: https://github.com/CCBR/MOSuite/issues
    about: If you encountered an error while running the MOSuite R Package (i.e. _not_ via Galaxy), please report the bug in the MOSuite repo.
